# Generated by Django 5.2.3 on 2025-06-20 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("listings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="card",
            name="public_description",
            field=models.TextField(
                blank=True,
                help_text="Publicly visible description of the card, its features, or notable aspects.",
            ),
        ),
    ]
